DeliveryDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("customer.urls", namespace="customer")),
    path("restaurant/", include("restaurant.urls", namespace="restaurant")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from customer.views import Index, About, Order, Menu, MenuSearch

app_name = "customer"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("about/", About.as_view(), name="about"),
    path("order/", Order.as_view(), name="order"),
    path("menu/", Menu.as_view(), name="menu"),
    path("menu/search/", MenuSearch.as_view(), name="menu-search"),
]

restaurant/urls.py
from django.urls import path

from restaurant.views import Dashboard

app_name = "restaurant"

urlpatterns = [
    path("dashboard/", Dashboard.as_view(), name="dashboard")
]

customer/models.py
from django.db import models


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="menu_images/")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ManyToManyField('Category', related_name="item")

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class OrderModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    items = models.ManyToManyField(MenuItem, related_name="order", blank=True)
    name = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=50, blank=True)
    street = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=13, blank=True, null=True)
    zip_code = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"Order: {self.created_at.strftime('%b %d %I: %M %p')}"

restaurant/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from .models import MenuItem, Category, OrderModel


class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'customer/index.html')


class About(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'customer/about.html')


class Order(View):
    def get(self, request, *args, **kwargs):
        # get every item from each category
        appetizers = MenuItem.objects.filter(category__name__contains='Appetizer')
        entres = MenuItem.objects.filter(category__name__contains='Entre')
        desserts = MenuItem.objects.filter(category__name__contains='Dessert')
        drinks = MenuItem.objects.filter(category__name__contains='Drink')

        # pass into context
        context = {
            'appetizers': appetizers,
            'entres': entres,
            'desserts': desserts,
            'drinks': drinks,
        }

        return render(request, 'customer/order.html', context)

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        email = request.POST.get("email")
        street = request.POST.get("street")
        city = request.POST.get("city")
        phone = request.POST.get("phone")
        zip_code = request.POST.get("zip_code")

        order_items = {
            'items': []
        }

        items = request.POST.getlist('items[]')

        for item in items:
            menu_item = MenuItem.objects.get(pk__contains=int(item))
            item_data = {
                'id': menu_item.pk,
                'name': menu_item.name,
                'price': menu_item.price
            }

            order_items['items'].append(item_data)

        price = 0
        item_ids = []

        for item in order_items['items']:
            price += item['price']
            item_ids.append(item['id'])

        order = OrderModel.objects.create(
            price=price,
            name=name,
            email=email,
            street=street,
            city=city,
            phone=phone,
            zip_code=zip_code
        )
        order.items.add(*item_ids)

        send_mail(
            'Order has been accepted !',
            'Thank you for your order your food will be ordered as soon as possible, total price: ' + f"{price}",
            'iislom280@gmail.com',
            [email],
            fail_silently=False,
        )

        context = {
            'items': order_items['items'],
            'price': price
        }

        return render(request, 'customer/order_confirmation.html', context)


class Menu(View):
    def get(self, request, *args, **kwargs):
        menu = MenuItem.objects.all()

        context = {
            "menu_items": menu,
        }

        return render(request, "customer/menu.html", context)


class MenuSearch(View):
    def get(self, request, *args, **kwargs):
        q = self.request.GET.get("q")
        menu = MenuItem.objects.filter(
            Q(name__icontains=q) | Q(price__icontains=q) | Q(description__icontains=q)
        )
        context = {
            "menu_items": menu,
        }
        return render(request, "customer/menu.html", context)

restaurant/views.py
from django.utils.timezone import datetime

from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from customer.models import OrderModel


class Dashboard(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        today = datetime.today()
        orders = OrderModel.objects.filter(
            created_at__year=today.year,
            created_at__month=today.month,
            created_at__day=today.day
        )

        total_revenue = 0

        for order in orders:
            total_revenue += order.price

        context = {
            "orders": orders,
            "total_revenue": total_revenue,
            "total_orders": len(orders),
        }
        return render(request, 'restaurant/dashboard.html', context)

    def test_func(self):
        return self.request.user.groups.filter(
            name="staff").exists()

templates/customer/about.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
                <h1>About Us</h1>
            </div>
        </div>
        <div class="row justify-content-center mt-1">
            <div class="card col-md-5 col-sm-12 offset-md-1 p-4 text-center">
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
                    quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                    Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
                    quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                    Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
                    quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                    Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/customer/index.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
                <h1>Online Food Delivery Service</h1>
            </div>
        </div>
        <div class="row justify-content-center mt-1">
            <div class="card col-md-5 col-sm-12 offset-md-1 p-4 text-center">
                <h2>Place an Order !</h2>
                <a href="{% url 'customer:order' %}" class="btn btn-outline-primary">Order Now !</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/customer/menu.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 text-center">
                <h1>What's On Our Menu</h1>
            </div>
        </div>

        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 text-center">
                <form method="GET" action="{% url 'customer:menu-search' %}">
                    <div class="md-form mt-0 active-cyan-2">
                        <input class="form-control" name="q" type="text" placeholder="search our menu"
                               aria-label="Search" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-success mt-3">Search</button>
                </form>
            </div>
        </div>

        <div class="row justify-content-center">
            {% for menu in menu_items %}
                <div class="col-md-4 col-sm-12 text-center mb-5 mt-5">
                    <img class="rounded" src="{{ menu.image.url }}" alt="" height="300" width="350">
                    <h5 class="mt-3">{{ menu.name }}</h5>
                    <p>Price: {{ menu.price }}</p>
                    <p>{{ menu.description }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/customer/order.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-1">
            <div class="col-md-12 col-sm-12 p-4">
                <form method="POST">
                    {% csrf_token %}
                    <div class="pt-5">
                        {% for app in appetizers %}
                            <div class="row">
                                <div class="col-md-2 col-sm-12">
                                    <img class="rounded" src="{{ app.image.url }}" width="150" height="100"/>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <div class="d-flex flex-row">
                                        <div class="form-group form-check">
                                            <input type="checkbox" name="items[]" class="form-check-input"
                                                   value="{{ app.pk }}">
                                            <label class="form-check-label">{{ app.name }}'''</label>
                                        </div>
                                        <p class="font-weight-bold pl-5"> ${{ app.price }}'''</p>
                                    </div>
                                    <p>{{ app.description }}</p>
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                    </div>

                    <div class="pt-5">
                        {% for entre in entres %}
                            <div class="row mt-4">
                                <div class="col-md-2 col-sm-12">
                                    <img class="rounded" src="{{ entre.image.url }}" width="150" height="100"/>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <div class="d-flex flex-row">
                                        <div class="form-group form-check">
                                            <input type="checkbox" name="items[]" class="form-check-input"
                                                   value="{{ entre.pk }}">
                                            <label class="form-check-label">{{ entre.name }}'''</label>
                                        </div>
                                        <p class="font-weight-bold pl-5"> ${{ entre.price }}'''</p>
                                    </div>
                                    <p>{{ entre.description }}</p>
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                    </div>

                    <div class="pt-5">
                        {% for dessert in desserts %}
                            <div class="row mt-4">
                                <div class="col-md-2 col-sm-12">
                                    <img class="rounded" src="{{ dessert.image.url }}" width="150" height="100"/>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <div class="d-flex flex-row">
                                        <div class="form-group form-check">
                                            <input type="checkbox" name="items[]" class="form-check-input"
                                                   value="{{ dessert.pk }}">
                                            <label class="form-check-label">{{ dessert.name }}'''</label>
                                        </div>
                                        <p class="font-weight-bold pl-5"> ${{ dessert.price }}'''</p>
                                    </div>
                                    <p>{{ dessert.description }}</p>
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                    </div>

                    <div class="pt-5">
                        {% for drink in drinks %}
                            <div class="row mt-4">
                                <div class="col-md-2 col-sm-12">
                                    <img class="rounded" src="{{ drink.image.url }}" width="150" height="100"/>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <div class="d-flex flex-row">
                                        <div class="form-group form-check">
                                            <input type="checkbox" name="items[]" class="form-check-input"
                                                   value="{{ drink.pk }}">
                                            <label class="form-check-label">{{ drink.name }}'''</label>
                                        </div>
                                        <p class="font-weight-bold pl-5"> ${{ drink.price }}'''</p>
                                    </div>
                                    <p>{{ drink.description }}</p>
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                    </div>

                    <div class="form-group pt-3">
                        <label for="name">Full Name</label>
                        <input required type="text" class="form-control" placeholder="Your name" name="name">
                    </div>
                    <div class="form-group pt-3">
                        <label for="name">Email Address</label>
                        <input required type="text" class="form-control" placeholder="example@company.com" name="email">
                    </div>
                    <div class="form-group pt-3">
                        <label for="name">Street Address</label>
                        <input required type="text" class="form-control" placeholder="1234 Main St" name="street">
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group pt-3">
                                <label for="name">City</label>
                                <input required type="text" class="form-control" placeholder="Ferghana" name="city">
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group pt-3">
                                <label for="name">Phone</label>
                                <input required type="text" class="form-control" placeholder="+998" name="phone">
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group pt-3">
                                <label for="name">Zip Code</label>
                                <input required type="text" class="form-control" placeholder="100500" name="zip_code">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark mt-5">Place Order!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/customer/order_confirmation.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>Order Submitted!</h1>
            <p>You should receive a confirmation email soon.</p>
            <a href="{% url 'customer:index' %}">Go to the homepage</a>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12 text-center">
            <h3 class="pb-3">Order Summary:</h3>
            {% for item in items %}
                <p>{{ item.name }} <span class="pl-3"> ${{ item.price }}</span></p>
            {% endfor %}

            <p class="font-weight-bold pt-4">Total: ${{ price }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Delivery</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
            rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
            rel="stylesheet"/>
</head>
<body>
{% include 'layouts/navbar.html' %}
{% block content %}
{% endblock %}
{% include 'layouts/footer.html' %}
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
></script>
</body>
</html>

templates/layouts/footer.html
<footer class="page-footer font-small indigo fixed-bottom bg-primary text-white">
    <div class="footer-copyright text-center py-3">&copy; 2020 Copyright:
        <a class="text-white" href="{% url 'customer:index' %}">
            Delivery
        </a>
        <a class="text-white" href="{% url 'restaurant:dashboard' %}">
            Restaurant Login
        </a>

    </div>
</footer>

templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary indigo">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'customer:index' %}">Delivery</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:menu' %}">Menu</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:order' %}">
                        Place an Order !
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/restaurant/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Restaurant</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
            rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
            rel="stylesheet"/>
</head>
<body>
{% include 'restaurant/navbar.html' %}
{% block content %}
{% endblock %}
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
></script>
</body>
</html>

templates/restaurant/dashboard.html
{% extends 'restaurant/base.html' %}
{% block content %}
    <div class="container" style="margin-top: 50px">
        <div class="row justify-content-center">
            <div class="card col-md-5 mr-3" style="margin-right: 50px">
                <h4 class="text-center pt-2">
                    Today's revenue
                </h4>
                <h1 class="text-center text-success">
                    ${{ total_revenue }}
                </h1>
            </div>

            <div class="card col-md-5" style="margin-right: 50px">
                <h4 class="text-center pt-2">
                    Today's Total Orders
                </h4>
                <h1 class="text-center text-danger">
                    {{ total_orders }}
                </h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 mt-5">
                <table class="table table-hover table-stripped">
                    <thead>
                    <tr>
                        <th scope="col">
                            Order ID
                        </th>
                        <th scope="col">
                            Price
                        </th>
                        <th scope="col">
                            Name
                        </th>
                        <th scope="col">
                            Email
                        </th>
                        <th scope="col">
                            Street
                        </th>
                        <th scope="col">
                            City
                        </th>
                        <th scope="col">
                            Phone
                        </th>
                        <th scope="col">
                            Zip_code
                        </th>
                        <th scope="col">
                            Paid:
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order.pk }}</th>
                            <td>${{ order.price }}</td>
                            <td>{{ order.name }}</td>
                            <td>{{ order.email }}</td>
                            <td>{{ order.street }}</td>
                            <td>{{ order.city }}</td>
                            <td>{{ order.phone }}</td>
                            <td>{{ order.zip_code }}</td>
                            <td>
                                {% if order.is_paid %}
                                    <i class="fas fa-check text-success"></i>
                                {% else %}
                                    <i class="fas fa-times text-danger"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/restaurant/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary indigo">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'customer:index' %}">Delivery</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">

            </ul>
            <ul class="navbar-nav">

            </ul>
        </div>
    </div>
</nav>